# export SLACK_BOT_TOKEN=xxxx
# export SLACK_APP_TOKEN=xxxx
# export GITLAB_TOKEN=xxxx
# export OPENAI_API_KEY=xxxx
# docker-compose --project-name reportbot up
# docker-compose --project-name reportbot down
services:
  reportbot:
    container_name: reportbot
    image: reportbot
    environment:
      SLACK_BOT_TOKEN: "${SLACK_BOT_TOKEN}"
      SLACK_APP_TOKEN: "${SLACK_APP_TOKEN}"
      GITLAB_TOKEN: "${GITLAB_TOKEN}"
      OPENAI_API_KEY: "${OPENAI_API_KEY}"
    volumes:
      - ./reportbot-data:/app/data
      - ./reportbot-reports:/app/reports
      - ./override/config.yaml:/app/config.yaml:ro
      - ./override/llm_glossary.yaml:/app/llm_glossary.yaml:ro
      - ./llm_classification_guide.md:/app/llm_classification_guide.md:ro